"""additional_column_upcoming_and_backref_post

Revision ID: 1d04ce4ad828
Revises: 37670b4dfb11
Create Date: 2022-02-14 10:30:09.247099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d04ce4ad828'
down_revision = '37670b4dfb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'upcomings', ['upc_id'], ['id_upc'])
    op.add_column('upcomings', sa.Column('developer', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('genre', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('synopsis', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'upcomings', 'category', ['id_category'], ['id_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upcomings', type_='foreignkey')
    op.drop_column('upcomings', 'synopsis')
    op.drop_column('upcomings', 'genre')
    op.drop_column('upcomings', 'publisher')
    op.drop_column('upcomings', 'developer')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'upc_id')
    # ### end Alembic commands ###
