"""'add_kontol'

Revision ID: 2a3581abf356
Revises: d22d960337f4
Create Date: 2022-02-24 11:22:48.735594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3581abf356'
down_revision = 'd22d960337f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kontol',
    sa.Column('anjing', sa.Integer(), nullable=False),
    sa.Column('babi', sa.String(length=100), nullable=True),
    sa.Column('puki', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('anjing')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kontol')
    # ### end Alembic commands ###
