"""add_cover_change_backref_upcoming

Revision ID: 37670b4dfb11
Revises: 8c568d8eac95
Create Date: 2022-02-12 21:14:31.576657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37670b4dfb11'
down_revision = '8c568d8eac95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('cover_picture', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('platform', sa.String(length=255), nullable=True))
    op.drop_constraint('upcomings_ibfk_1', 'upcomings', type_='foreignkey')
    op.create_foreign_key(None, 'upcomings', 'category', ['id_category'], ['id_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upcomings', type_='foreignkey')
    op.create_foreign_key('upcomings_ibfk_1', 'upcomings', 'categories', ['id_category'], ['id_cat'])
    op.drop_column('upcomings', 'platform')
    op.drop_column('upcomings', 'cover_picture')
    # ### end Alembic commands ###
