"""add_thumbnail_lastseen

Revision ID: 4ebde32c227d
Revises: 5703c9050511
Create Date: 2022-02-09 20:13:57.077760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebde32c227d'
down_revision = '5703c9050511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('posts', 'thumbnail')
    # ### end Alembic commands ###
