"""'add_change_post_table_category'

Revision ID: 5f0cf26b8a21
Revises: 76a33c1fe44b
Create Date: 2022-02-03 21:28:11.668762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0cf26b8a21'
down_revision = '76a33c1fe44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('category')
    )
    op.add_column('posts', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'category', ['category_id'], ['id_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_column('posts', 'description')
    op.drop_table('category')
    # ### end Alembic commands ###
