"""'add_thumbnail_upcoming'

Revision ID: 5f5ca8ef00e4
Revises: 88004cb624db
Create Date: 2022-02-17 22:12:15.742692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5ca8ef00e4'
down_revision = '88004cb624db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('thumbnail_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'thumbnail_picture')
    # ### end Alembic commands ###
