"""drop_subcategory_on_category

Revision ID: 65c70c06f525
Revises: c5d16bc7f015
Create Date: 2022-04-12 14:18:35.234984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65c70c06f525'
down_revision = 'c5d16bc7f015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_category_sub_category', table_name='category')
    op.drop_column('category', 'sub_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sub_category', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('_category_sub_category', 'category', ['category', 'sub_category'], unique=False)
    # ### end Alembic commands ###
