"""('add_update_To_collections')

Revision ID: 70f34b334c25
Revises: 91cf47f08cf0
Create Date: 2022-05-25 11:02:05.181181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70f34b334c25'
down_revision = '91cf47f08cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.add_column('upcomings', sa.Column('updated', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'updated')
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_width', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
