"""'added_level_date-mod'

Revision ID: 73cac9672591
Revises: e5667df0ca56
Create Date: 2022-01-26 11:30:09.955656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cac9672591'
down_revision = 'e5667df0ca56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
