"""additional_Ccolumn_upcoming

Revision ID: 7605f2a1e079
Revises: 5f5ca8ef00e4
Create Date: 2022-02-22 09:57:35.984976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7605f2a1e079'
down_revision = '5f5ca8ef00e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('starring', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('boxoffice', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('language', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('budget', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('mpaa', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('based', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'based')
    op.drop_column('upcomings', 'mpaa')
    op.drop_column('upcomings', 'budget')
    op.drop_column('upcomings', 'language')
    op.drop_column('upcomings', 'boxoffice')
    op.drop_column('upcomings', 'starring')
    # ### end Alembic commands ###
