"""'remove_unique_upcomings'

Revision ID: 76a33c1fe44b
Revises: 41b681be85b2
Create Date: 2022-02-03 13:11:45.126163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a33c1fe44b'
down_revision = '41b681be85b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='upcomings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'upcomings', ['name'], unique=False)
    # ### end Alembic commands ###
