"""additional_column_for_upcoming

Revision ID: 80326d5b9abb
Revises: 1d04ce4ad828
Create Date: 2022-02-15 08:48:53.917762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80326d5b9abb'
down_revision = '1d04ce4ad828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('producer', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('studio', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('series', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('engine', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('mode', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('episode', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('duration', sa.String(length=255), nullable=True))
    op.add_column('upcomings', sa.Column('source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcomings', 'source')
    op.drop_column('upcomings', 'duration')
    op.drop_column('upcomings', 'episode')
    op.drop_column('upcomings', 'mode')
    op.drop_column('upcomings', 'engine')
    op.drop_column('upcomings', 'series')
    op.drop_column('upcomings', 'studio')
    op.drop_column('upcomings', 'producer')
    # ### end Alembic commands ###
