"""'add_relation_upc_user'

Revision ID: 88004cb624db
Revises: 80326d5b9abb
Create Date: 2022-02-16 10:44:06.542805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88004cb624db'
down_revision = '80326d5b9abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcomings', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upcomings', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upcomings', type_='foreignkey')
    op.drop_column('upcomings', 'id_user')
    # ### end Alembic commands ###
