"""add_multi_unique

Revision ID: 9a812b4fd933
Revises: cc10890f7030
Create Date: 2022-04-11 14:34:16.966390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a812b4fd933'
down_revision = 'cc10890f7030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_category_sub_category', 'category', ['category', 'sub_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_category_sub_category', 'category', type_='unique')
    # ### end Alembic commands ###
