"""'add_column_likepost'

Revision ID: 9e2b3a2cd957
Revises: 241b87a9076a
Create Date: 2022-02-24 11:29:56.051695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e2b3a2cd957'
down_revision = '241b87a9076a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likepost', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('likepost', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'likepost', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'likepost', 'posts', ['post_id'], ['id'])
    op.drop_column('likepost', 'anjing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likepost', sa.Column('anjing', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'likepost', type_='foreignkey')
    op.drop_constraint(None, 'likepost', type_='foreignkey')
    op.drop_column('likepost', 'post_id')
    op.drop_column('likepost', 'user_id')
    # ### end Alembic commands ###
