"""'Initial_Migration'

Revision ID: 9e71cfc2cd91
Revises: 
Create Date: 2022-01-23 13:04:04.343966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e71cfc2cd91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_color', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_color')
    # ### end Alembic commands ###
