"""add_unique_subcategory

Revision ID: a40f67bf3b4d
Revises: cdfedf53a4fc
Create Date: 2022-04-11 13:43:12.028712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40f67bf3b4d'
down_revision = 'cdfedf53a4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['sub_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
