"""'add_user-post_relation'

Revision ID: a710862e8839
Revises: 9e2b3a2cd957
Create Date: 2022-02-28 08:33:03.630341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a710862e8839'
down_revision = '9e2b3a2cd957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kontol')
    op.add_column('users', sa.Column('id_post', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'posts', ['id_post'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'id_post')
    op.create_table('kontol',
    sa.Column('anjing', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('babi', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('puki', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('anjing'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
