"""add_news_type_post

Revision ID: c5d16bc7f015
Revises: 9a812b4fd933
Create Date: 2022-04-12 13:55:51.852393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d16bc7f015'
down_revision = '9a812b4fd933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('news_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'news_type')
    # ### end Alembic commands ###
