"""drop_oldconstraint_add_new

Revision ID: cc10890f7030
Revises: a40f67bf3b4d
Create Date: 2022-04-11 14:30:33.254454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc10890f7030'
down_revision = 'a40f67bf3b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('category', table_name='category')
    op.drop_index('sub_category', table_name='category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sub_category', 'category', ['sub_category'], unique=False)
    op.create_index('category', 'category', ['category'], unique=False)
    # ### end Alembic commands ###
