"""add_tags_and_lenght_post

Revision ID: cdfedf53a4fc
Revises: f1ec341e284b
Create Date: 2022-04-09 19:02:33.058804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfedf53a4fc'
down_revision = 'f1ec341e284b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
