"""'add_category_and_upcoming'

Revision ID: d4d1a8b9c2b7
Revises: 1d077f18acaa
Create Date: 2022-02-01 21:23:59.498615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d1a8b9c2b7'
down_revision = '1d077f18acaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=255), nullable=True),
    sa.Column('sub_categories', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_cat')
    )
    op.create_table('upcomings',
    sa.Column('id_upc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_released', sa.Date(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_cat'], ),
    sa.PrimaryKeyConstraint('id_upc')
    )
    op.add_column('posts', sa.Column('cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['cat_id'], ['id_cat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'cat_id')
    op.drop_table('upcomings')
    op.drop_table('categories')
    # ### end Alembic commands ###
