"""'add_language_to_post'

Revision ID: f1ec341e284b
Revises: a710862e8839
Create Date: 2022-04-04 21:10:21.962518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1ec341e284b'
down_revision = 'a710862e8839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'id_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_post', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'posts', ['id_post'], ['id'])
    op.drop_column('posts', 'language')
    # ### end Alembic commands ###
